on: [push]

env:
  AWS_DEFAULT_REGION: 'ap-northeast-1'
  AWS_ACCOUNT_ID: "848738341109"

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # needed to interact with GitHub's OIDC Token endpoint.
      contents: read
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3

      - name: Cache CDK Dependency
        uses: actions/cache@v3
        id: cache_cdk_dependency_id
        env:
          cache-name: cache-cdk-dependency
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }}
          restore-keys: ${{ runner.os }}-build-${{ env.cache-name }}-

      - name: Install CDK Dependency
        if: ${{ steps.cache_cdk_dependency_id.outputs.cache-hit != 'true' }}
        run: npm install

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/aws-cert-leaders-deploy-role
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - name: cdk diff
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_version: '2.56.0'
          cdk_subcommand: 'diff'
          actions_comment: true

      - name: run test
        run: npm run test

      - name: cdk deploy
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_version: '2.56.0'
          cdk_subcommand: 'deploy'
          cdk_args: '--require-approval never'
          actions_comment: false

      - name: cdk synth
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: 'synth'
          cdk_version: '2.56.0'
          working_dir: '.'